FROM node:22.23.3-alpine

RUN apk add --no-cache openssl

WORKDIR /usr/src/app
RUN chown node:node /usr/src/app
USER node

COPY --chown=node:node package.json package-lock.json ./
RUN npm ci

COPY --chown=node:node prisma ./prisma
RUN npx prisma generate

COPY --chown=node:node . .

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
